# Generated by Django 4.0.5 on 2023-04-21 15:46

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAdminData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=36, null=True)),
                ('myfilter', models.CharField(max_length=128, null=True)),
                ('todo', models.CharField(max_length=1024, null=True)),
                ('link', models.CharField(max_length=1024, null=True)),
                ('link_description', models.CharField(max_length=1024, null=True)),
                ('chatgpt', models.CharField(max_length=2048, null=True)),
                ('chatgpt_status', models.CharField(max_length=128, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyCaptcha',
            fields=[
                ('key', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=512, null=True)),
                ('subject', models.CharField(max_length=9, null=True)),
                ('response', models.CharField(max_length=9, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('problem', models.CharField(max_length=64, null=True)),
                ('message', models.TextField(max_length=6048, null=True)),
                ('warning', models.BooleanField(null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyInternalError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=None, max_length=255)),
                ('error', models.CharField(max_length=512, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyIpBanList',
            fields=[
                ('key', models.CharField(max_length=36, null=True)),
                ('ip', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255, null=True)),
                ('date_banned', models.DateTimeField(null=True)),
                ('expiration_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyIpManagement',
            fields=[
                ('ip', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('score', models.IntegerField(null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('last_request_date', models.DateTimeField(null=True)),
                ('total_request_count', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyLinkBetweenUserAndSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('old_key', models.CharField(max_length=255, null=True)),
                ('new_key', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyNewLetter',
            fields=[
                ('key', models.CharField(max_length=36, null=True)),
                ('email', models.EmailField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('warning', models.BooleanField(null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MySessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=None, max_length=255)),
                ('action', models.CharField(max_length=512, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyStatisticData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windows', models.BigIntegerField(null=True)),
                ('mac', models.BigIntegerField(null=True)),
                ('linux', models.BigIntegerField(null=True)),
                ('android', models.BigIntegerField(null=True)),
                ('ios', models.BigIntegerField(null=True)),
                ('other_os', models.BigIntegerField(null=True)),
                ('chrome', models.BigIntegerField(null=True)),
                ('firefox', models.BigIntegerField(null=True)),
                ('edge', models.BigIntegerField(null=True)),
                ('safari', models.BigIntegerField(null=True)),
                ('opera', models.BigIntegerField(null=True)),
                ('other_browser', models.BigIntegerField(null=True)),
                ('desktop', models.BigIntegerField(null=True)),
                ('tablet', models.BigIntegerField(null=True)),
                ('mobile', models.BigIntegerField(null=True)),
                ('from_referal', models.BigIntegerField(null=True)),
                ('from_direct', models.BigIntegerField(null=True)),
                ('from_browser', models.BigIntegerField(null=True)),
                ('total_get_trafic', models.BigIntegerField(null=True)),
                ('total_post_trafic', models.BigIntegerField(null=True)),
                ('total_session_trafic', models.BigIntegerField(null=True)),
                ('total_ip_trafic', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyTraficData',
            fields=[
                ('get_trafic', models.BigIntegerField(null=True)),
                ('post_trafic', models.BigIntegerField(null=True)),
                ('total_trafic', models.BigIntegerField(null=True)),
                ('session_trafic', models.BigIntegerField(null=True)),
                ('ip_trafic', models.BigIntegerField(null=True)),
                ('referal_trafic', models.BigIntegerField(null=True)),
                ('direct_trafic', models.BigIntegerField(null=True)),
                ('browser_trafic', models.BigIntegerField(null=True)),
                ('date', models.DateTimeField(default=None, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MyVerifCode',
            fields=[
                ('key', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=512, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyVisitor',
            fields=[
                ('key', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('os', models.CharField(max_length=512, null=True)),
                ('browser', models.CharField(max_length=512, null=True)),
                ('device', models.CharField(max_length=512, null=True)),
                ('language', models.CharField(max_length=512, null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('country', models.CharField(max_length=512, null=True)),
                ('city', models.CharField(max_length=512, null=True)),
                ('user_agent', models.CharField(max_length=512, null=True)),
                ('referer', models.URLField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('fingerprint', models.CharField(max_length=1000, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
