# Generated by Django 4.0.5 on 2023-04-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRanking',
            fields=[
                ('user_key', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, null=True)),
                ('fname', models.CharField(max_length=256, null=True)),
                ('lname', models.CharField(max_length=256, null=True)),
                ('loc', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(max_length=32, null=True)),
                ('activity', models.CharField(max_length=32, null=True)),
                ('description', models.CharField(max_length=513, null=True)),
                ('cvfilename', models.CharField(max_length=65, null=True)),
                ('cvfiledata', models.TextField(null=True)),
                ('logodata', models.TextField(null=True)),
                ('verified', models.BooleanField(default=False)),
                ('ipaddress', models.GenericIPAddressField(null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
