# Generated by Django 4.0.5 on 2023-04-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_myranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myranking',
            old_name='logodata',
            new_name='logofiledata',
        ),
        migrations.RemoveField(
            model_name='myranking',
            name='cvfilename',
        ),
        migrations.AddField(
            model_name='myranking',
            name='email',
            field=models.EmailField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='myranking',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='myranking',
            name='fname',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='myranking',
            name='lname',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='myranking',
            name='loc',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='myranking',
            name='user_key',
            field=models.CharField(default=None, max_length=129, primary_key=True, serialize=False),
        ),
    ]
