# Generated by Django 4.0.5 on 2023-04-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_logodata_myranking_logofiledata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myranking',
            name='cvfiledata',
            field=models.ImageField(blank=True, null=True, upload_to='posts_image/'),
        ),
    ]
