# Generated by Django 4.0.5 on 2023-04-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_myranking_cvfiledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myranking',
            name='cvfiledata',
            field=models.FileField(blank=True, null=True, upload_to='cdn/pdf/'),
        ),
        migrations.AlterField(
            model_name='myranking',
            name='logofiledata',
            field=models.ImageField(blank=True, null=True, upload_to='cdn/logo/'),
        ),
    ]
