# Generated by Django 4.0.5 on 2023-04-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_myranking_cvfiledata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(max_length=129, null=True)),
                ('note', models.IntegerField(null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
