# Generated by Django 4.0.5 on 2023-05-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_myopinion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyNewLetter',
        ),
        migrations.AlterField(
            model_name='myranking',
            name='cvfiledata',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='myranking',
            name='logofiledata',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
