# Generated by Django 4.1 on 2023-05-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_myuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myranking',
            name='loc',
        ),
        migrations.AddField(
            model_name='myranking',
            name='city',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='myranking',
            name='dep',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='myranking',
            name='tarif',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
